'use client';
import { useState, useEffect, useRef } from 'react';

/**
 * Blog search powered by Pagefind (static, build-time index).
 * Renders a search input + results dropdown that queries /pagefind/pagefind.js,
 * which is generated by `pagefind --site out` after `next build`.
 *
 * Falls back gracefully if pagefind isn't loaded (e.g. dev mode).
 */
export default function BlogSearch({ placeholder = 'Search posts…' }) {
  const [query, setQuery] = useState('');
  const [results, setResults] = useState([]);
  const [loading, setLoading] = useState(false);
  const [open, setOpen] = useState(false);
  const [pagefindReady, setPagefindReady] = useState(false);
  const pagefind = useRef(null);
  const debounceRef = useRef(null);

  // Pagefind indexes the raw static output, so result URLs look like
  // /blog/<slug>.html. The live site serves posts at /<slug> (the edge
  // worker strips the /blog prefix and only knows clean URLs), so .html
  // links 404. Normalize to the canonical clean URL.
  function toCleanUrl(raw) {
    let u = (raw || '').replace(/\.html$/, '');
    if (u === '/blog') return '/';
    if (u.startsWith('/blog/')) u = u.slice('/blog'.length);
    return u || '/';
  }

  useEffect(() => {
    let cancelled = false;
    async function init() {
      try {
        // Pagefind ships at /pagefind/pagefind.js after build
        const mod = await import(/* webpackIgnore: true */ '/pagefind/pagefind.js');
        await mod.options({ excerptLength: 25 });
        if (!cancelled) {
          pagefind.current = mod;
          setPagefindReady(true);
        }
      } catch {
        // Pagefind not available (likely dev mode); search will show a message
      }
    }
    init();
    return () => {
      cancelled = true;
    };
  }, []);

  useEffect(() => {
    if (!query.trim() || !pagefindReady) {
      setResults([]);
      setLoading(false);
      return;
    }
    setLoading(true);
    clearTimeout(debounceRef.current);
    debounceRef.current = setTimeout(async () => {
      try {
        const search = await pagefind.current.search(query);
        const top = await Promise.all(
          search.results.slice(0, 8).map((r) => r.data())
        );
        setResults(top.map((r) => ({ ...r, url: toCleanUrl(r.url) })));
      } catch {
        setResults([]);
      } finally {
        setLoading(false);
      }
    }, 150);
    return () => clearTimeout(debounceRef.current);
  }, [query, pagefindReady]);

  return (
    <div className="relative max-w-xl mx-auto">
      <div className="relative">
        <svg
          className="absolute left-4 top-1/2 -translate-y-1/2 w-5 h-5"
          style={{ color: 'var(--text-muted)' }}
          fill="none"
          stroke="currentColor"
          viewBox="0 0 24 24"
        >
          <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M21 21l-6-6m2-5a7 7 0 11-14 0 7 7 0 0114 0z" />
        </svg>
        <input
          type="text"
          placeholder={placeholder}
          value={query}
          onChange={(e) => {
            setQuery(e.target.value);
            setOpen(true);
          }}
          onFocus={() => setOpen(true)}
          onBlur={() => setTimeout(() => setOpen(false), 150)}
          maxLength={200}
          className="w-full pl-12 pr-12 py-3.5 rounded-xl glass-card text-sm focus:outline-none focus:ring-2 focus:ring-[var(--accent)]/40 focus:border-[var(--accent)]/40 transition-all"
          style={{ color: 'var(--text-primary)' }}
        />
        {query && (
          <button
            type="button"
            onClick={() => {
              setQuery('');
              setResults([]);
            }}
            className="absolute right-3 top-1/2 -translate-y-1/2 w-7 h-7 rounded-full flex items-center justify-center hover:bg-[var(--border-subtle)] transition-colors"
            aria-label="Clear search"
          >
            <svg className="w-4 h-4" style={{ color: 'var(--text-muted)' }} fill="none" stroke="currentColor" viewBox="0 0 24 24">
              <path strokeLinecap="round" strokeLinejoin="round" strokeWidth={2} d="M6 18L18 6M6 6l12 12" />
            </svg>
          </button>
        )}
      </div>

      {open && query.trim() && (
        <div className="absolute z-30 left-0 right-0 mt-2 rounded-xl glass-card shadow-2xl overflow-hidden max-h-[70vh] overflow-y-auto">
          {!pagefindReady && (
            <div className="p-6 text-sm" style={{ color: 'var(--text-muted)' }}>
              Search loads after the production build (run <code>npm run build</code>).
            </div>
          )}
          {pagefindReady && loading && (
            <div className="p-6 text-sm" style={{ color: 'var(--text-muted)' }}>
              Searching…
            </div>
          )}
          {pagefindReady && !loading && results.length === 0 && (
            <div className="p-6 text-sm" style={{ color: 'var(--text-muted)' }}>
              No results for <span className="font-semibold" style={{ color: 'var(--text-primary)' }}>{query}</span>
            </div>
          )}
          {pagefindReady && !loading && results.length > 0 && (
            <ul className="divide-y" style={{ borderColor: 'var(--border-subtle)' }}>
              {results.map((r, i) => (
                <li key={i}>
                  <a
                    href={r.url}
                    className="block p-4 hover:bg-[var(--accent)]/5 transition-colors"
                  >
                    <div className="flex items-baseline justify-between gap-3 mb-1">
                      <h4
                        className="font-semibold leading-snug"
                        style={{ color: 'var(--text-primary)' }}
                        dangerouslySetInnerHTML={{ __html: r.meta?.title || 'Untitled' }}
                      />
                      <span className="text-[10px] uppercase tracking-wider whitespace-nowrap" style={{ color: 'var(--text-muted)' }}>
                        {r.meta?.read || ''}
                      </span>
                    </div>
                    <p
                      className="text-xs leading-relaxed line-clamp-2"
                      style={{ color: 'var(--text-secondary)' }}
                      dangerouslySetInnerHTML={{ __html: r.excerpt }}
                    />
                    <div className="mt-2 text-[11px]" style={{ color: 'var(--text-muted)' }}>
                      {r.meta?.author && <span>{r.meta.author}</span>}
                    </div>
                  </a>
                </li>
              ))}
            </ul>
          )}
        </div>
      )}
    </div>
  );
}
